### ISSUE TITLE
Nitrogen device type has no versions available in production

### ISSUE THREAD

**Issue by agherzan** [balena-os/balena-fsl-arm#57]
Steps to reproduce:
- create a new app for nitrogen board
- try to download an image for provisioning a new device

Observed behaviour: image maker doesn't offer any versions to download.

Expected behaviour: image maker should offer at least one version to download.

Can't reproduce on staging. Only production seems to lack images.

**Comment by savpek** [comment]
When will these be available? I am currently building this repository manually with PR #58  because of this issue.

**Comment by savpek** [comment]
And that build fails for problems with rust 😢

**Comment by spanceac** [comment]
Hey @savpek,

The #58 PR is getting constantly updated and work is not ready.

I think that the PR will get ready for merge in ~1 week so you can manually build the image.
The image that you can download from the dashboard will probably reach production in about 2 weeks. This means that the image will be fully tested by us.

**Comment by floion** [comment]
This device type has been discontinued
